name: Create a release candidate branch

on:
  schedule:
    - cron: "45 4 * * 5" # Every Friday at 4:45 am Central

  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - id: get-date
        run: echo "::set-output todays-date=$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - run: |
          git config --local user.email "github@kazoohr.com"
          git config --local user.name "KazooHR GitHub Workflows"
      - id: branch-exists-check
        run: |
          if [ -n "$(git ls-remote --heads origin RC-${{ steps.get-date.outputs.todays-date }})" ]; then
            echo "::set-output name=branch-exists::1"
          fi
      - run: |
          git checkout -b RC-${{ steps.get-date.outputs.todays-date }}
          git push --set-upstream origin \
            RC-${{ steps.get-date.outputs.todays-date }}
          git tag RC-${{ steps.get-date.outputs.todays-date }}-001
          git push --tags
        if: steps.branch-exists-check.outputs.branch-exists == '1'
