name: Create a release candidate branch

on:
  schedule:
    - cron: "45 4 * * 5" # Every Friday at 4:45 am Central

  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - id: get-branch-name
        run: echo "::set-output name=RC-$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - run: |
          git config --local user.email "github@kazoohr.com"
          git config --local user.name "KazooHR GitHub Workflows"
      - id: branch-exists-check
        run: |
          if [ -n "$(git ls-remote --heads origin ${{ steps.get-branch-name.outputs.name }})" ]; then
            echo "::set-output name=exists::1"
          fi
      - run: |
          git checkout -b ${{ steps.get-branch-name.outputs.name }}
          git push --set-upstream origin \
            ${{ steps.get-branch-name.outputs.name }}
          git tag ${{ steps.get-branch-name.outputs.name }}-001
          git push --tags
        if: steps.branch-exists-check.outputs.exists == '1'
