name: Release candidate branch maintanence

on:
  push:
    branches:
      - "RC-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" # RC-YYYY-MM-DD

jobs:
  release-candidate-tags:
    runs-on: ubuntu-latest
    steps:
      - name:
        id: clean-up-old-package-versions
        uses: stripethree/rc-branch-action@action-artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
