name: Release candidate branch maintanence

on:
  push:
    branches:
      - "RC-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" # RC-YYYY-MM-DD

jobs:
  create-rc-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - id: get_next_tag
        run: node dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git tag ${{ steps.get_next_tag.outputs.next_tag }}
          git push --tags
        if: steps.get_next_tag.outputs.next_tag != ''
