name: Release candidate branch maintanence

on:
  push:
    branches:
      - "RC-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" # RC-YYYY-MM-DD

jobs:
  create-rc-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get last tag
        id: get_last_tag
        run: echo "##[set-output name=last_tag;]$(git tag -l --sort=-version:refname "${GITHUB_REF##*/}-???" | head -n 1)"
      - name: Show last tag
        run: echo ${{ steps.get_last_tag.outputs.last_tag }}
