name: Release candidate branch maintanence

on:
  push:
    branches:
      - "RC-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" # RC-YYYY-MM-DD

jobs:
  create-rc-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Get the last tag and create the label for the next tag
        id: get_tags
        run: node dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
